config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  resources :personal_infos
  get "editinfo", to: "personal_infos#show"
  patch "personal_infos#edit", to: "personal_infos#update"
  resources :games do
    resources :notes, only: [:create, :destroy]
  end

  root to: 'users#show'
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "edit_info", to: "personal_infos#edit"

  resources :users
  resources :genres
  get 'user/show' => 'users#show', as:'show'
  # get 'genres/:id' => 'genres#show', as: 'find_friends'
  get 'genres/index'
  get 'genres/show'

  get "edit_genre", to: "users#edit"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api, defaults: { format: 'json'} do
    get 'games/search', to: 'games#search'
    get 'personal_infos/search', to: 'personal_infos#search'
    get 'genres/search', to: 'genres#search'
    get 'users/search', to: 'users#search'
    get 'notes/search', to: 'notes#search'
    post "/login", to: "sessions#login"
    post "/signup", to: "sessions#signup"

    resources :todos
    resources :games
    resources :notes
    resources :genres
    resources :personal_infos
    resources :users
  end
end

app/models/personal_info.rb
class PersonalInfo < ApplicationRecord
  belongs_to :user
end

app/controllers/api/personal_infos_controller.rb
class Api::PersonalInfosController < ApiController
  def index
    render json: PersonalInfo.all
  end

  def show
    info = PersonalInfo.find_by(id: params[:id])
    if info
      render json: info
    else
      render json: {error: 'Info not found'}, status: 404
    end
  end

  def search
    render json: PersonalInfo.where('country LIKE ?', "%#{params[:country]}%")
  end

  # def create
  #   user = User.find(params[:user_id])
  #   info = user.personal_info.new(title: params[:title], note: params[:note], score: params[:score], date: params[:date] )
  #   if info.save
  #     render json: info
  #   else
  #     render json: { error: 'Cannot create info'}, status: 404
  #   end
  # end

end

app/controllers/personal_infos_controller.rb
class PersonalInfosController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  
  # GET /personal_infos/1 or /personal_infos/1.json
  def show
    @user = current_user
    if @current_user.personal_info == nil
      @info = PersonalInfo.create! [age: 18, country: 'earth', phone: '123456789', twitter: '@twitter', user: current_user]
      @personal_info = @info
    else
      @personal_info = @current_user.personal_info
    end
  end  

  # GET /personal_infos/1/edit
  def edit
    @info = @user.personal_info
  end

  # POST /personal_infos or /personal_infos.json
  def create
    # if session[:user_id]
    #   @user = User.find_by(id: session[:user_id])
    #   @user_id = @user.id
    @personal_info = current_user.personal_info.new(personal_info_params)
    if @personal_info.save
      redirect_to root_path(@user), notice: "Personal info was successfully created."
      # format.json { render :show, status: :created, location: @personal_info }
    else
      redirect_to root_path(@user), notice: "Personal info was successfully created."
      # format.json { render json: @personal_info.errors, status: :unprocessable_entity }
      # end
    end
  end

  # PATCH/PUT /personal_infos/1 or /personal_infos/1.json
  def update
    respond_to do |format|
      if @personal_info.update(personal_info_params)
        format.html { redirect_to personal_info_url(@personal_info), notice: "Personal info was successfully updated." }
        format.json { render :show, status: :ok, location: @personal_info }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @personal_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_infos/1 or /personal_infos/1.json
  def destroy
    @personal_info.destroy

    respond_to do |format|
      format.html { redirect_to personal_infos_url, notice: "Personal info was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
    # @personal_info = current_user.personal_info.find(params[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def personal_info_params
    params.require(:personal_info).permit(:age, :country, :phone, :twitter)
  end
end

app/helpers/personal_infos_helper.rb
module PersonalInfosHelper
end

app/views/personal_infos/_form.html.erb
<%= form_with(model: personal_info) do |form| %>
  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.number_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit "submit"%>
  </div>
<% end %>

app/views/personal_infos/_personal_info.html.erb
<div id="<%= dom_id personal_info %>">
  <p>
    <strong>Age:</strong>
    <%= personal_info.age.to_s %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= personal_info.country %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= personal_info.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= personal_info.twitter %>
  </p>

</div>

app/views/personal_infos/edit.html.erb
<h1>Editing personal info</h1>

<%= render "form", personal_info: @personal_info %>

<br>




<div>
  <%= link_to "Back to personal infos", editinfo_path %>
</div>

app/views/personal_infos/index.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<!--<h1>Personal infos</h1>-->

<!--<div id="personal_infos">-->
  <%# @personal_infos.each do |personal_info| %>
    <%#= render personal_info %>
<!--    <p>-->
    <%#= link_to "Edit", edit_personal_info_path(personal_info) %>
      <%#= link_to "Show this personal info", personal_info %>
<!--    </p>-->
  <%# end %>
<!--</div>-->


<%#= link_to "Back to Home", show_path %>

app/views/personal_infos/new.html.erb
<h1>Create personal info</h1>

<%= render "form", personal_info: @personal_info %>

<br>

<div>
  <%= link_to "Back to personal infos", personal_infos_path %>
</div>

app/views/personal_infos/show.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<table>
  <tr>
    <th>Name:</th>
    <td><%= @user['name'] %></td>
  </tr>
  <tr>
    <th>Age:</th>
    <td><%= @personal_info['age'] %></td>
  </tr>
  <tr>
    <th>Country:</th>
    <td><%= @personal_info['country'] %></td>
  </tr>
  <tr>
    <th>Phone:</th>
    <td><%= @personal_info['phone'] %></td>
  </tr>
  <tr>
    <th>Twitter:</th>
    <td><%= @personal_info['twitter'] %></td>
  </tr>
</table>


<div>
  <%#= link_to "Edit this personal info", edit_personal_info_path(@personal_info) %>
  <%= link_to "Back to Home page", show_path %>
</div>