config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  resources :personal_infos
  get "editinfo", to: "personal_infos#show"
  patch "personal_infos#edit", to: "personal_infos#update"
  resources :games do
    resources :notes, only: [:create, :destroy]
  end

  root to: 'users#show'
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "edit_info", to: "personal_infos#edit"

  resources :users
  resources :genres
  get 'user/show' => 'users#show', as:'show'
  # get 'genres/:id' => 'genres#show', as: 'find_friends'
  get 'genres/index'
  get 'genres/show'

  get "edit_genre", to: "users#edit"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api, defaults: { format: 'json'} do
    get 'games/search', to: 'games#search'
    get 'personal_infos/search', to: 'personal_infos#search'
    get 'genres/search', to: 'genres#search'
    get 'users/search', to: 'users#search'
    get 'notes/search', to: 'notes#search'
    post "/login", to: "sessions#login"
    post "/signup", to: "sessions#signup"

    resources :todos
    resources :games
    resources :notes
    resources :genres
    resources :personal_infos
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :personal_info, dependent: :destroy
  has_many :games, dependent: :destroy
  has_many :notes, through: :games, source: :notes, dependent: :destroy
  has_secure_password
  validates :email, presence: true

  has_and_belongs_to_many :genres

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  def index
    render json: User.all
  end

  def show
    user = User.find_by(id: params[:id])
    if user
      render json: user
    else
      render json: {error: 'User not found'}, status: 404
    end
  end

  def search
    render json: User.where('email LIKE ?', "%#{params[:email]}%")
  end

  # def create
  #   user = User.new(name: params[:name], email: params[:email], pa: params[:score] )
  #   if user.save
  #     render json: user
  #   else
  #     render json: { error: 'Cannot create user'}, status: 404
  #   end
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def edit

  end

  def show
    @user = current_user
    @games = @user.games.all
    @notes = @user.notes
    @genres = @user.genres
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "user created"
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Games App', show_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">


      <% if logged_in? %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <%= link_to 'Home', show_path, class:"nav-link active" %>
            </li>
            <li class="nav-item">
            <%= link_to 'My games', games_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to 'Find Friends', genres_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to 'About me', editinfo_path, class:"nav-link" %>
            </li>
            </ul>

                <div style='float: right; color: white '>
                Logged in as <%= current_user.name %> |
                <%= link_to 'Logout', logout_path, method: :delete %>
                </div>
    <% else %>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <%= link_to 'Log in', login_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to 'Sign up', sign_up_path, class:"nav-link" %>
            </li>
            </ul>


<% end %>

    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<h1>Add genre game I like </h1>


<!--<div id="genres">-->
  <%# @genres.each do |genre| %>
<!--    <div><%# genre.name %></div>-->
  <%# end %>
<!--</div>-->


<div>
  <%= form_with model: @genres, url: new_genre_path do |form| %>
    <div>
      <%= form.label :name, style: "display block" %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.submit 'Add New genre' %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

        <div>
          <%= form_with model: @user, url: sign_up_path do |form| %></div>
            <% if @user.errors.any? %>
              <div class="alert alert-danger">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this game from being saved:</h2>

                <ul>
                  <% @user.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label"><%= form.label :name%></label>
              <%=  form.text_field :name, placeholder: "Welcome"  %>
            </div>
            <div class="mb-3">
              <%= form.label :email%>
              <%= form.text_field :email, placeholder: "123456@email.com" %>
            </div>
            <div class="mb-3">
              <%= form.label :password%>
              <%= form.password_field :password, placeholder: "password" %>
            </div>


    <div class="mb-3">
    <%= form.submit "Sign up" %>
    </div>
  <% end %>

<!--          <div>-->
<!--            <%#= form_with model: @personal_info do |form| %></div>-->
<!--              <div>-->
                <%#= form.label :age%>
                <%#= form.text_field :age, placeholder: "18" %>
<!--              </div>-->
<!--              <div>-->
                <%#= form.label :country%>
                <%#= form.password_field :country, placeholder: "Canada" %>
<!--              </div>-->
<!--              <div>-->
                <%#= form.label :phone%>
                <%#= form.password_field :phone, placeholder: "239 1234 1234" %>
<!--              </div>-->
<!--              <div>-->
                <%#= form.label :twitter%>
                <%#= form.password_field :twitter, placeholder: "@joeteew" %>
<!--              </div>-->
            <%# end %>

app/views/users/show.html.erb
<h1>Hi,<%= @user.name %>(<%= @user.email %>)</h1>

</br>
<div>
  <h4>Genres you love:</h4>

<!--  <div id="notes">-->
    <%#= @user.personal_info.age %>
<!--  </div>-->

  <div id="genres">
    <% @genres.each do |genre| %>
      <div><%= genre.name %></div>
    <% end %>
<!--    <div><%#= link_to 'Add', edit_user_path(@user) %></div>-->
  </div>
</div>

<!--<div>-->
  <%#= form_for([@genres, @genres.new]) do |form| %>
<!--    <div>-->
      <%#= form.label :name, style: "display block" %>
      <%#= form.text_field :name %>
<!--    </div>-->
<!--    <div>-->
      <%#= form.submit 'Add' %>
<!--    </div>-->
  <%# end %>
<!--</div>-->
</br>


<div>
  You have played
  <% @games.each do |game| %>
    <div><%= link_to game.title, game_path(game) %></div>
  <% end %>
</div>

</br>
<div>
  All your notes
  <div>
    <% @notes.each do |note| %>

      <div>Score: <%= note.score %></div>
      <div><%= note.note %></div>
      <div><%= "(#{time_ago_in_words note.created_at} ago)" %></div>
      <br>
    <% end %>
  </div>
</div>