config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  resources :personal_infos
  get "editinfo", to: "personal_infos#show"
  patch "personal_infos#edit", to: "personal_infos#update"
  resources :games do
    resources :notes, only: [:create, :destroy]
  end

  root to: 'users#show'
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "edit_info", to: "personal_infos#edit"

  resources :users
  resources :genres
  get 'user/show' => 'users#show', as:'show'
  # get 'genres/:id' => 'genres#show', as: 'find_friends'
  get 'genres/index'
  get 'genres/show'

  get "edit_genre", to: "users#edit"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api, defaults: { format: 'json'} do
    get 'games/search', to: 'games#search'
    get 'personal_infos/search', to: 'personal_infos#search'
    get 'genres/search', to: 'genres#search'
    get 'users/search', to: 'users#search'
    get 'notes/search', to: 'notes#search'
    post "/login", to: "sessions#login"
    post "/signup", to: "sessions#signup"

    resources :todos
    resources :games
    resources :notes
    resources :genres
    resources :personal_infos
    resources :users
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy

  has_one_attached :avatar
end

app/controllers/api/games_controller.rb
class Api::GamesController < ApiController
  before_action :auth_games, only: [ :destroy]
  def index
    render json: Game.all
  end

  def show
    game = Game.find_by(id: params[:id])
    if game
      render json: game, include: :notes
    else
      render json: {error: 'Game not found'}, status: 404
    end
  end

  def search
    render json: Game.where('title LIKE ?', "%#{params[:title]}%")
  end

  def create
    user = User.find(params[:user_id])
    game = user.games.new(title: params[:title], genre: params[:genre], platform: params[:platform], short_description: params[:short_description] )
    if game.save
      render json: game
    else
      render json: { error: 'Cannot create game'}, status: 404
    end
  end

  def destroy
    user = User.find(params[:user_id])
    user.games.find(params[:id]).destroy!
    render json: {notice: 'Successfully destroy the game'}
  end

  private
  def auth_games
    current_id = User.find(params[:user_id]).id
    user_id = Game.find_by(id: params[:id]).user_id
    render json: { errir: "Unauthorized"}, status: :unauthorized unless current_id == user_id
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = current_user.games.all
    @user = current_user
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = current_user.games.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = current_user.games.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = current_user.games.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:title, :genre, :platform, :short_description, :avatar)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :avatar, style: "display: block" %>
    <%= form.file_field :avatar %>
  </div>
  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.text_field :genre %>
  </div>

  <div>
    <%= form.label :platform, style: "display: block" %>
    <%= form.text_field :platform %>
  </div>

  <div>
    <%= form.label :short_description, style: "display: block" %>
    <%= form.text_field :short_description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Avatar:</strong>
    <% if game.avatar.attached? %>
      <%=image_tag game.avatar, width: "200px" %>
    <% end %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= game.title %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= game.genre %>
  </p>

  <p>
    <strong>Platform:</strong>
    <%= game.platform %>
  </p>

  <p>
    <strong>Short description:</strong>
    <%= game.short_description %>
  </p>

</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<h1>Games</h1>



<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<div class="game">
  <h3><%= content_tag :span, "#{@game.title} (#{@game.genre})"%></h3>
  <%= link_to 'Edit', edit_game_path(@game) %>
</div>

<%#= render @game %>

<div id="notes">
  <%= render @game.notes %>
</div>

<br>

<div>
  <%= form_for([@game, @game.notes.new]) do |form| %>
    <div class="mb-3">
      <div class="form-label"><%= form.label :title, style: "display block" %></div>
      <%= form.text_field :title %>
    </div>
    <div class="mb-3">
      <div class="form-label"><%= form.label :score, style: "display block" %></div>
      <%= form.text_field :score %>
    </div>
    <div class="mb-3">
      <div class="form-label"><%= form.label :note, style: "display: block" %></div>
      <%= form.text_area :note, size: '25×5' %>
    </div>
    <div>
      <%= form.submit 'Add New Note' %>
    </div>
  <% end %>
</div>
<br>
<div>
  <%#= link_to "Edit this game", edit_game_path(@game) %>
  <%= link_to "Back to games", games_path %>

  <%= link_to "Destroy this game", @game, method: :delete %>
</div>